# Generated by Django 3.2.6 on 2021-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='company',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='subject',
            field=models.CharField(max_length=240),
        ),
    ]
