# Generated by Django 3.2.6 on 2021-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0002_auto_20210813_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='company',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
