# Generated by Django 3.2.6 on 2021-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0003_auto_20210813_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callbackform',
            name='comment',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
