# Generated by Django 3.2.6 on 2021-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0005_remove_callbackform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='comment',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='problem_description',
            field=models.CharField(max_length=2000),
        ),
    ]
