# Generated by Django 3.2.6 on 2021-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0006_auto_20210815_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
