# Generated by Django 3.2.6 on 2021-08-16 09:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0007_alter_callbackform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callbackform',
            name='support_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
